Module5 task1
htmlacademy-ecmascript/926589-cinemaddict-17 pull request #13
Opened 2022-06-11 10:01 UTC by KuzKonBor

2022-06-12 04:43 UTC, Dima-Dim reviewed
Не жалей удалять закомментированный код. Когда понадобиться напишешь лучше ;)

2022-06-12 04:44 UTC, Dima-Dim requested changes
В опубликованной версии https://htmlacademy-ecmascript.github.io/926589-cinemaddict-17/13/, при открытии карточки фильма в консоли ошибка:
```
common.js:9 Uncaught TypeError: e.findIndex is not a function
    at t.value (common.js:9:23)
    at Object.value [as click] (film-card-presenter.js:98:5)
    at HTMLImageElement.value (film-card-view.js:105:20)
```

2022-06-16 18:09 UTC, KuzKonBor commented
> В опубликованной версии https://htmlacademy-ecmascript.github.io/926589-cinemaddict-17/13/, при открытии карточки фильма в консоли ошибка:
> 
> ```
> common.js:9 Uncaught TypeError: e.findIndex is not a function
>     at t.value (common.js:9:23)
>     at Object.value [as click] (film-card-presenter.js:98:5)
>     at HTMLImageElement.value (film-card-view.js:105:20)
> ```

Исправил

2022-06-17 12:28 UTC, Dima-Dim commented on src/model/film-cards-model.js
> +const InitialNumberOfMovieCards = 9;
https://up.htmlacademy.ru/ecmascript/17/criteries#b5

2022-06-17 12:29 UTC, merged