Перекомитил в новую ветку Module2 task1
htmlacademy-ecmascript/926589-cinemaddict-17 pull request #7
Opened 2022-05-16 19:53 UTC by KuzKonBor

2022-05-17 11:28 UTC, Dima-Dim commented
Перед отправкой на проверку решить конфликт, опубликовать, проверить что всё как и хотел.

2022-05-17 16:57 UTC, KuzKonBor commented
Убрал конфликты... Блин а ведь проверял перед отправкой есть они или нет, они что через какое-то время могут погрузиться?

2022-05-17 17:00 UTC, Dima-Dim commented
> Убрал конфликты... Блин а ведь проверял перед отправкой есть они или нет, они что через какое-то время могут погрузиться?

Возможно есть какая-то не очень большая задержка. Нужно дождаться зелёных галочек.

2022-05-17 17:04 UTC, KuzKonBor commented
Он мне пишет All checks have failed 1 failing check это пропуске по паре строк их можно автоматом как то исправить прямо в гите?

2022-05-17 17:05 UTC, Dima-Dim commented
> Он мне пишет All checks have failed 1 failing check это пропуске по паре строк их можно автоматом как то исправить прямо в гите?

Можно, но лучше это делать локально. И проверку линтером и исправления.

2022-05-17 17:14 UTC, KuzKonBor commented
Странно у меня линтер не ругается на пропуск 2-ух строк, только на 3-ех:)
Это вообще считается за ошибку? Кстати спасибо за видео помогло прямь очень, если есть еще полезные видео или что еще что поможет укрепить основы очень жду:)

2022-05-17 17:19 UTC, Dima-Dim commented
> Странно у меня линтер не ругается на пропуск 2-ух строк, только на 3-ех:) Это вообще считается за ошибку? Кстати спасибо за видео помогло прямь очень, если есть еще полезные видео или что еще что поможет укрепить основы очень жду:)

Рад что материал помог. А ошибки линтера считаются за ошибки :)

2022-05-18 06:19 UTC, Dima-Dim requested changes
Ну и ошибки литера нужно тоже исправить.

2022-05-18 06:19 UTC, Dima-Dim commented on src/fish/card.js
> +const getFilmCards = () => ({
Прям `Cards` и на выходе массив этих самых `Card`?

2022-05-18 06:19 UTC, Dima-Dim commented on src/fish/comment.js
> +const EMOTION = ['smile', 'sleeping', 'puke', 'angry'];
А тут наоборот, одна эмоция?

2022-05-18 06:19 UTC, Dima-Dim commented on src/fish/comment.js
> +const getArrayComments = () =>({
И вот так везде :)

2022-05-18 06:19 UTC, Dima-Dim commented on src/fish/data.js
> +const POSTERS = [
Вот тут нормально ;)

2022-05-18 06:19 UTC, Dima-Dim commented on src/fish/data.js
> +const ALTERNATIVE_TITLE = [
А тут НЕ нормально :)

2022-05-18 06:19 UTC, Dima-Dim commented on src/view/detailed-information-film-view.js
> +export{FilmDetailsNewCommentContainerView, FilmDetailsUlContainerView, FilmDetailsFormView, FilmDetailsView, FilmDetailsTopContainerView, FilmDetailsBottomContainerView, FilmDetailsComentsView};
https://up.htmlacademy.ru/ecmascript/17/criteries#b28

2022-05-20 15:31 UTC, closed without merging

2022-05-20 15:32 UTC, KuzKonBor commented
Чет изменения не пушит как я понял пока открыт этот пулреквест.