Module3 task1
htmlacademy-ecmascript/926589-cinemaddict-17 pull request #9
Opened 2022-05-23 15:45 UTC by KuzKonBor

2022-05-26 06:50 UTC, Dima-Dim requested changes
https://htmlacademy-ecmascript.github.io/926589-cinemaddict-17/9/
При закрытии модального окна с помощью Esc в консоли
board-presenter.js:61 Uncaught TypeError: document.removeElementListener is not a function
    at HTMLDocument.t (board-presenter.js:61:18)

2022-05-26 06:50 UTC, Dima-Dim commented on src/model/film-cards-model.js
> +  #filmCard = Array.from({length: 5}, getFilmCard);
5 - магическое число.

2022-05-26 19:30 UTC, KuzKonBor commented on src/model/film-cards-model.js
> +  #filmCard = Array.from({length: 5}, getFilmCard);
Исправил.

2022-05-27 06:42 UTC, Dima-Dim approved these changes

2022-05-27 06:42 UTC, merged